
const ADD_TEAM = 'ADD_TEAM';
const EDIT_NAME = 'EDIT_NAME';
const EDIT_ADDRESS1 = 'EDIT_ADDRESS1';
const EDIT_ADDRESS2 = 'EDIT_ADDRESS2';

export default {
    ADD_TEAM,
    EDIT_NAME,
    EDIT_ADDRESS1,
    EDIT_ADDRESS2
}